# Generated by Django 2.2.5 on 2019-09-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_translation_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
